### ISSUE TITLE
True, false, null, [] flagged as invalid

### ISSUE THREAD

**Issue by senkrad76** [RougeWare/JSON-for-Notepad--#1]
I'm getting values flagged on this:

{
    key-1 : **null,**
    key-2 : **false,**
    "array" : [ {
                 key-3a : "STRING",
                 key-3b: **[],**
                 key-3c: 1,
                 key-3d: true
    } ]
}

Argh, formattings off... a null, true, false, [] followed by a , are getting hit as invalid (highlighted red)

Using this to format jsons from Grafana if that helps

**Comment by Supuhstar** [comment]
Thanks, @senkrad76! I believe it's fixed now. Could you update and confirm?

**Comment by Supuhstar** [comment]
Closing for now. Feel free to reopen or resubmit if not fixed.

**Comment by senkrad76** [comment]
That works!

I've been using this to help with editing JSONs for Grafana, additional changes I made as well:

```
<Keywords name="Folders in code2, middle">[], {}</Keywords>
```

Allowed the folding to work properly

and

```
<Keywords name="Keywords2">null []</Keywords>
```

Styles [] as null... maybe should change this to a 3rd style as an empty set instead of null
